name: datasurface-validator
description: 'DataSurface Pull Request Validator'
inputs:
  github_token:
    required: true
  base_repository:
    required: true
  head_repository:
    required: true
  head_branch:
    required: true

runs:
  using: 'composite'

  steps:
    - name: Checkout PR code
      uses: actions/checkout@v2
      with:
        token: ${{ inputs.github_token }}
        ref: ${{ inputs.head_branch }}
        path: pr

    - name: Checkout main branch code
      uses: actions/checkout@v2
      with:
        token: ${{ inputs.github_token }}
        ref: 'main'
        path: main

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ${{ github.workspace }}/main/requirements.txt

    - name: Run check script
      run: python -m datasurface.handler.action ${{ github.workspace }}/main ${{ github.workspace }}/pr
      env:
          GITHUB_TOKEN: ${{ inputs.github_token }}      
          BASE_REPOSITORY: ${{ inputs.base_repository }}
          HEAD_REPOSITORY: ${{ inputs.head_repository }}
          HEAD_BRANCH: ${{ inputs.head_branch }}
